/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	deploycontrolv1alpha1 "github.com/kongyi-ibm/k8s-deployment-operator/pkg/apis/deploycontrol/v1alpha1"
	versioned "github.com/kongyi-ibm/k8s-deployment-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kongyi-ibm/k8s-deployment-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kongyi-ibm/k8s-deployment-operator/pkg/client/listers/deploycontrol/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DeployDaemonInformer provides access to a shared informer and lister for
// DeployDaemons.
type DeployDaemonInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DeployDaemonLister
}

type deployDaemonInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDeployDaemonInformer constructs a new informer for DeployDaemon type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDeployDaemonInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDeployDaemonInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDeployDaemonInformer constructs a new informer for DeployDaemon type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDeployDaemonInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeploycontrolV1alpha1().DeployDaemons(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeploycontrolV1alpha1().DeployDaemons(namespace).Watch(options)
			},
		},
		&deploycontrolv1alpha1.DeployDaemon{},
		resyncPeriod,
		indexers,
	)
}

func (f *deployDaemonInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDeployDaemonInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *deployDaemonInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&deploycontrolv1alpha1.DeployDaemon{}, f.defaultInformer)
}

func (f *deployDaemonInformer) Lister() v1alpha1.DeployDaemonLister {
	return v1alpha1.NewDeployDaemonLister(f.Informer().GetIndexer())
}
