/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kongyi-ibm/k8s-deployment-operator/pkg/apis/deploycontrol/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDeployDaemons implements DeployDaemonInterface
type FakeDeployDaemons struct {
	Fake *FakeDeploycontrolV1alpha1
	ns   string
}

var deploydaemonsResource = schema.GroupVersionResource{Group: "deploycontrol.k8s.io", Version: "v1alpha1", Resource: "deploydaemons"}

var deploydaemonsKind = schema.GroupVersionKind{Group: "deploycontrol.k8s.io", Version: "v1alpha1", Kind: "DeployDaemon"}

// Get takes name of the deployDaemon, and returns the corresponding deployDaemon object, and an error if there is any.
func (c *FakeDeployDaemons) Get(name string, options v1.GetOptions) (result *v1alpha1.DeployDaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(deploydaemonsResource, c.ns, name), &v1alpha1.DeployDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeployDaemon), err
}

// List takes label and field selectors, and returns the list of DeployDaemons that match those selectors.
func (c *FakeDeployDaemons) List(opts v1.ListOptions) (result *v1alpha1.DeployDaemonList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(deploydaemonsResource, deploydaemonsKind, c.ns, opts), &v1alpha1.DeployDaemonList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DeployDaemonList{ListMeta: obj.(*v1alpha1.DeployDaemonList).ListMeta}
	for _, item := range obj.(*v1alpha1.DeployDaemonList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested deployDaemons.
func (c *FakeDeployDaemons) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(deploydaemonsResource, c.ns, opts))

}

// Create takes the representation of a deployDaemon and creates it.  Returns the server's representation of the deployDaemon, and an error, if there is any.
func (c *FakeDeployDaemons) Create(deployDaemon *v1alpha1.DeployDaemon) (result *v1alpha1.DeployDaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(deploydaemonsResource, c.ns, deployDaemon), &v1alpha1.DeployDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeployDaemon), err
}

// Update takes the representation of a deployDaemon and updates it. Returns the server's representation of the deployDaemon, and an error, if there is any.
func (c *FakeDeployDaemons) Update(deployDaemon *v1alpha1.DeployDaemon) (result *v1alpha1.DeployDaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(deploydaemonsResource, c.ns, deployDaemon), &v1alpha1.DeployDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeployDaemon), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDeployDaemons) UpdateStatus(deployDaemon *v1alpha1.DeployDaemon) (*v1alpha1.DeployDaemon, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(deploydaemonsResource, "status", c.ns, deployDaemon), &v1alpha1.DeployDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeployDaemon), err
}

// Delete takes name of the deployDaemon and deletes it. Returns an error if one occurs.
func (c *FakeDeployDaemons) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(deploydaemonsResource, c.ns, name), &v1alpha1.DeployDaemon{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDeployDaemons) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(deploydaemonsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DeployDaemonList{})
	return err
}

// Patch applies the patch and returns the patched deployDaemon.
func (c *FakeDeployDaemons) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DeployDaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(deploydaemonsResource, c.ns, name, pt, data, subresources...), &v1alpha1.DeployDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeployDaemon), err
}
