apiVersion: v1
kind: Service
metadata:
  name: deploydaemon
  labels:
    component: deploydaemon
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8081
      name: port8081
  selector:
    app: demoqaauth-ts-app
    expose: online