apiVersion: deploycontrol.k8s.io/v1alpha1
kind: DeployDaemon
metadata:
  name: test-deploydaemon-1
spec:
  tenant: demo
  environment: qa
  envtype: auth
  component: ts-app
  image: kongyibj/bluedocker:v1
  version: 9.0.1.3
  instance: 4
  expose: online
  configRef: demoqaauth
  secrets:
    - paramName: VAULT_TOKEN
      secretName: demoqaauth_vaulttoken
